### ISSUE TITLE
Expressions lines won't unfold

### ISSUE THREAD

**Issue by ayashjorden** [paschmann/rasa-ui#59]
Hello rasa-ui!
I've been playing with RASA for a couple of weeks now, wish I would find this UI earlier. great job!

Under agent/1/intent/1 - Expressions list, when I click on the arrow button, it won't unfold. I've getting a JS error:
![image](https://user-images.githubusercontent.com/4204371/39064947-e5df38be-44d8-11e8-9a48-a4e678b7df8b.png)

Expected is what I see in rasa-ui README.md:
![image](https://user-images.githubusercontent.com/4204371/39064982-0904702a-44d9-11e8-8c18-f0ba0930e23d.png)

Am I missing something here?

Also, what is "Intent Reponses" ? optional replies from rasa-core? or actions?

Thank you in advance,
Jorden

**Comment by pradeepmvn** [comment]
@ayashjorden The Entity text should be highlighted first with the "link" icon and then the down arrow button should unfold the entity selection. 

Intent responses can either come from a webhook or a Static text. This is what sent to the clients for a specific intent. You can have multiple static responses and rasa-ui will pick randomly. This doesn't need rasa-core to be enabled. It provides an easy mechanism for a simple smart-talk agent.  Hope this helps.

**Comment by ayashjorden** [comment]
@pradeepmvn , thank you for explaining that

How do I make rasaui use rasa_core?

**Comment by pradeepmvn** [comment]
@ayashjorden Rasa ui can model the actions, action templates and Stories for rasa_core. But since there is no endpoint to train rasa core over http, there is a manual step to start the server by downloading files from rasa-ui.  
You can also test you core predictions from the right side chat widget. It can get data from a webhook and display as well. Let us know if you need any other help.

I will close this issue. Feel free to open another one as needed.
